---
title: "Module 4 - Instructions"
author: "Oliver Engist"
date: "3/25/2020"
output: pdf_document
---

In the next assignment we want to replicate some plots from the paper "Female Socialization: How Daughters Affect Their Legislator Fathers' Voting on Women's Issues" (Washington, 2008). The paper explores whether having a daughter makes politicians more sensitive to women's rights issues and how this is reflected in their voting behavior. The main identifying assumption is that after controlling for the number of children, the gender composition is random. This might be violated if families that have a preference for girls keep having children until they have a girl. In this assignment we will prepare a dataset that allows us to test whether families engage in such a "female child stopping rule".

I encourage you to take a look at the paper, as we will come back to it later in the course. 

# Setup

* Load the libraries "Rio" and "tidyverse"
* Change the path of the working directory to your working directory.

```{r, message=FALSE}

library(rio)
library(tidyverse)
```

* import the data sets *basic.dta* and *genold108.dta*
* create a subset of the 108th congress from the *basic* dataset
* join this subset with the *genold* dataset

# Data preparation

* check table 1 in the appendix of the paper and decide which variables are necessary for the analysis (check the footnote for control variables)
* drop all other variables.
* Recode *genold* such that gender is a factor variable and missing values are coded as NAs.
* Recode *party* as a factor with 3 levels (D, R, I)
* Recode *rgroup* and *region* as factors.
* generate variables for age squared and service length squared
* create an additional variable of the number of children as factor variable

# Replicationg Table 1 from the Appendix

We haven't covered regressions in R yet. Use the function *lm()*. The function takes the regression model (formula) and the data as an input. The model is written as $y \sim x$, where $x$ stands for any linear combination of regressors (e.g. $y \sim x_1 + x_2 + female$). Use the help file to understand the function.

* Run the regression $total.children = \beta_0 + \beta_1 gender.oldest + \gamma'X$ where $\gamma$ stands for a vector of coefficients and $X$ is a matrix that contains all columns that are control variables.\footnote{This is just a short notation instead of writing the full model with all control variables $totchi = \beta_0 + \beta_1 genold + \gamma_1 age + \gamma_2 age^2 + \gamma_3 Democrat + ... + \epsilon$ which quickly gets out of hand for large models.}
* Save the main coefficient of interest ($\beta_1$)
* Run the same regression separately for Democrats and Republicans (assign the independent to one of the parties). Save the coefficient and standard error of *genold*
* Collect all the *genold* coefficients from the six regressions, including their standard errors and arrange them in a table as in the paper.
* print the table