---
title: "Module 4 - Instructions"
author: "Oliver Engist"
date: "March 23, 2020"
output: pdf_document
---

We load the College dataset from the ISLR package. ISLR is the R package from the book "Introduction to Statistical Learning in R", which provides a very accessible introduction to machine learning. It is freely available for download from the publisher's website.

```{r}
library(tidyverse)
library(magrittr)
library(ISLR)
data("College") # load the pre-installed college dataset

glimpse(College)

```

# Elite Colleges

We want to classify colleges into elite and non-elite colleges:

* Plot the distribution of *Top10perc* using the *hist()* function. 
* Find the 90th percentile of the variable Top10perc.
* Create a variable *Elite* that is equal to one if the college is among the top 10 percent of colleges regarding their percentage of Top 10 percent high-school graduates.

## What makes an elite college?

We would like to know in which dimensions elite and non-elite colleges differ. We therefore create a table where we display the mean of each variable for elite and non-elite colleges and a pair-wise t-test to test whether the difference is significant.

* calculate the mean of the variables *Private*, *Outstate*, *PhD*, *S.F.Ratio* and  *perc.alumni* separately for both elite and non-elite colleges. You can use *group_by()* and *summarize()* or any other functions that make your life easier.
* Arrange the table such that elite and non-elite college means have separate columns.
* Round the numbers if necessary using the *round()* function.
* Rename the columns.
* Now perform a t-test for each variable to test if the means are statistically different. Use a loop, map or any other way to do this efficiently.
* Store the t-statistic in a vector
* append this vector as a separate column.